### ISSUE TITLE
Milestone 0 - build systems

### ISSUE THREAD

**Issue by adriaandegroot** [arpa2/steamworks#1]
indication of intent, mid-december. The existing SteamWorks 
program does not follow the (changed) ARPA2 norms for builds. This trivial 
change should be committed to re-integrate SteamWorks builds into the ARPA2 
family. Additionally, the TLSPool repository must be updated to the same norms 
and confirmed to run on development systems.

 - [x] ARPA2CM build system
   - [x] Builds on FreeBSD
   - [x] Builds on KDE Neon (Debian)
 - [x] SteamWorks build system
   - [x] Builds on FreeBSD
   - [x] Builds on KDE Neon (Debian)
 - [x] Quick-DER build system
   - [x] Builds on FreeBSD
   - [x] Builds on KDE Neon (Debian)
 - [x] TLSPool build system
   - [x] Builds on FreeBSD
   - [x] Builds on KDE Neon (Debian)

**Comment by adriaandegroot** [comment]
Build with a consistent PREFIX, that's all.

**Comment by leenaars** [comment]
Once this is taken care of, I'll try the Nix version.

**Comment by adriaandegroot** [comment]
Quick-DER is a dependency of TLSPool, which needs fixing (again). It builds if you disable all the header-and-binding generation and do only the library. PR opened in QD repo to fix bugs in the library and patch up the tests.

**Comment by adriaandegroot** [comment]
# General

Use a consistent PREFIX for all the builds; for development purposes, you can use `make PREFIX=/tmp/sw && make install` most of the time, to build the entire stack in `/tmp/sw`. Omitting the PREFIX is possible, too, but will install somewhere on the system, usually `/usr/local`.

# ARPA2CM
No issues. (No tests, though)

# SteamWorks
No issues. (Limited tests)

# Quick-DER
Does not build out-of-the-box. Generation of header files may or may not work; insufficient checks on Python versions, available tools, etc. Recommended to first run make with prefix set, wait for build to fail, then:
```
    cd build
    cmake -DSPEC_RFC=OFF
    make && make install
```
Limited tests. Python tests are also run when no Python tools are built or installed.

# TLSPool
Has a lot of dependencies. Take note that you need GNUTLS with DANE support (e.g. 3.5.16, compiled with the `--enable-libdane` configure option). Does not build unless Quick-DER has generated and installed RFC headers (see above: they may or may not build, try it with `SPEC_RFC=ON` and hope for the best).

**Comment by vanrein** [comment]
Quick-DER started to build out of the box again with [the minor change I made yesterday](https://github.com/vanrein/quick-der/commit/f723cf8467df7fa507c879635fab18bb4c20c4a9).  There is no longer a need to switch off RFC or other headers.  This has been confirmed on a pristine Debian Stable system.

**Comment by adriaandegroot** [comment]
Quick-DER documentation updated to mention required packages / Python modules, but there should be a ticket there for checking that (asn1ate, six) are actually available before starting the compile.

**Comment by adriaandegroot** [comment]
- Build-system fixes applied to Quick DER and PR'ed for TLSPool
 - Code polishing PR'ed for TLSPool
 - New release of ARPA2CM tagged
 - New release of Quick DER tagged (for CI; clients are still OK with 1.2.4)
