### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by adriaandegroot** [arpa2/steamworks#2]
Milestone 1, schemata. The project proposal lists four LDAP 
schemata to be developed for domain data and four corresponding LDAP schemata 
for domain data validation expressions. The collected schemata are to be 
committed to the TLSPool repository along with documentation on 
configuring an LDAP server to use them.

 - [ ] Trusted roots
 - [ ] TLS Local identity
 - [ ] X509 and OpenPGP local identity
 - [ ] Disclosure-schema for selecting identities for remotes
 - [ ] LDAP Configuration documentation

**Comment by vanrein** [comment]
Part or this has been coursely documented in the [DIT graph](https://github.com/arpa2/idhub-service/blob/master/doc/dit.graphml) and its [rendering](https://github.com/arpa2/idhub-service/blob/master/doc/dit.pdf).  This intends to capture prior discussion between adriaandegroot & vanrein.

Note: These files were edited with the free [Yed Graph Editor](http://www.yworks.com/downloads#yEd) from yWorks.

**TODO:** The graph is indeed course.  It lags behind the actual [schema example](https://github.com/arpa2/idhub-service/blob/master/doc/servicedit.ldif) and [attributetypes/objectclasses](https://github.com/arpa2/idhub-service/blob/master/doc/arpa2-servicedir.schema) that we coined.  Once we know things work as intended, we can move OIDs from the experimental (666) branch to a final branch.

**Comment by adriaandegroot** [comment]
(Note that I don't have write-access to TLSPool, so these will go in my own fork and there will be a PR)

**Comment by adriaandegroot** [comment]
@vanrein the schemata you point to are IdentityHub schemas, which have no obvious relation to TLSPool. For instance, schema 3, disclosure-schema, is what is described `tlspool/doc/databases.rst`, section *Identity disclosure database*, which is not an object class occurring in those IDHub documents. But thanks anyway.

**Comment by adriaandegroot** [comment]
Closing this as "was part of a project that never executed". I don't think it's a useful thing anymore.
