### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by adriaandegroot** [arpa2/steamworks#4]
sample VM, mid february. A complete VM (Debian-based) with a 
running TLSPool, LDAP server, sample data and a pulley is to be delivered (due 
to file size, presumably on a USB stick) for testing purposes. This is to 
include at least one sample configuration for pulling TLSPool data for a single 
domain from LDAP. Note that the configuration of LDAP and TLSPool on a single 
host is unusual, but does not detract from the general usefulness of the test.

 - [ ] Debian VM created
 - [ ] OpenLDAP installed
   - [ ] Schemata configured
   - [ ] DIT populated with sample data
 - [ ] TLSPool installed
 - [ ] Pulley installed
 - [ ] Sample (LDIF?) modification scripts for DIT

**Comment by adriaandegroot** [comment]
Closing this as "was part of a project that never executed". I don't think it's a useful thing anymore.
